#!/usr/bin/env python3
"""Plot switch-side per-flow throughput for the 400G all-to-all scenario."""

from __future__ import annotations

import argparse
from pathlib import Path
from typing import Dict, Iterable, List, Tuple


Point = Tuple[float, float]
Series = Dict[str, List[Point]]


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "trace_file",
        help="A *.switch-flow-throughput.tr file generated by sird_400g_alltoall.",
    )
    parser.add_argument("--output", required=True, help="Output PNG path.")
    parser.add_argument(
        "--flows",
        default="",
        help="Comma-separated flow labels to plot, e.g. 4->1,1->2. Defaults to all flows.",
    )
    parser.add_argument(
        "--title",
        default="Switch-side per-flow throughput",
        help="Plot title.",
    )
    parser.add_argument(
        "--time-unit",
        choices=("us", "ms", "s"),
        default="ms",
        help="X-axis time unit.",
    )
    parser.add_argument(
        "--start-zero",
        action="store_true",
        help="Shift the first plotted sample to t=0.",
    )
    parser.add_argument(
        "--legend-cols",
        type=int,
        default=4,
        help="Legend column count.",
    )
    return parser.parse_args()


def parse_fields(line: str) -> Dict[str, str]:
    fields: Dict[str, str] = {}
    for token in line.strip().split():
        if "=" not in token:
            continue
        key, value = token.split("=", 1)
        fields[key] = value
    return fields


def convert_time(time_ns: float, unit: str) -> float:
    if unit == "us":
        return time_ns / 1e3
    if unit == "ms":
        return time_ns / 1e6
    return time_ns / 1e9


def load_trace(path: Path, time_unit: str) -> Series:
    series: Series = {}
    with path.open("r", encoding="utf-8") as f:
        for raw in f:
            raw = raw.strip()
            if not raw:
                continue
            parts = raw.split()
            fields = parse_fields(raw)
            label = fields.get("series")
            gbps = fields.get("instGbps")
            if not label or gbps is None:
                continue
            t = convert_time(float(parts[0]), time_unit)
            series.setdefault(label, []).append((t, float(gbps)))
    return series


def flow_sort_key(label: str) -> Tuple[int, int]:
    src, dst = label.split("->", 1)
    return int(src), int(dst)


def selected_flows(series: Series, requested: str) -> List[str]:
    if requested.strip():
        flows = [item.strip() for item in requested.split(",") if item.strip()]
        missing = [flow for flow in flows if flow not in series]
        if missing:
            raise SystemExit(f"missing flow(s) in trace: {', '.join(missing)}")
        return flows
    return sorted(series.keys(), key=flow_sort_key)


def shifted(points: Iterable[Point], offset: float) -> List[Point]:
    return [(t - offset, y) for t, y in points]


def main() -> int:
    args = parse_args()

    try:
        import matplotlib.pyplot as plt
    except ImportError:
        print("matplotlib is required")
        return 1

    path = Path(args.trace_file)
    series = load_trace(path, args.time_unit)
    flows = selected_flows(series, args.flows)
    if not flows:
        raise SystemExit("no flow series found")

    first_t = min(points[0][0] for points in series.values() if points)

    colors = [
        "#1f77b4",
        "#ff7f0e",
        "#2ca02c",
        "#d62728",
        "#9467bd",
        "#8c564b",
        "#e377c2",
        "#7f7f7f",
        "#bcbd22",
        "#17becf",
        "#264653",
        "#e76f51",
    ]
    linestyles = ["-", "--", "-.", ":"]

    plt.figure(figsize=(10.5, 6.2))
    for idx, flow in enumerate(flows):
        points = series[flow]
        if args.start_zero:
            points = shifted(points, first_t)
        xs = [x for x, _ in points]
        ys = [y for _, y in points]
        plt.plot(
            xs,
            ys,
            label=flow,
            linewidth=1.8,
            color=colors[idx % len(colors)],
            linestyle=linestyles[(idx // len(colors)) % len(linestyles)],
        )

    plt.title(args.title, fontsize=17)
    plt.xlabel(f"Time ({args.time_unit})", fontsize=14)
    plt.ylabel("Throughput (Gb/s)", fontsize=14)
    plt.grid(True, linestyle="--", alpha=0.28)
    plt.legend(
        title="Flow",
        ncol=args.legend_cols,
        frameon=False,
        fontsize=9.5,
        title_fontsize=10,
        loc="upper center",
        bbox_to_anchor=(0.5, -0.13),
    )
    plt.tight_layout(rect=(0, 0.06, 1, 1))

    out = Path(args.output)
    out.parent.mkdir(parents=True, exist_ok=True)
    plt.savefig(out, dpi=220)
    print(f"output_png: {out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
